[package]
name = "rust_tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
regex = "1.5.4"
rusqlite = "0.29.0"
statrs = "0.16.0"
nom = "7.1.0"
#rayon = "1.5.1"